### ISSUE TITLE
Use official Ruby SDK

### ISSUE THREAD

**Issue by tylerlong** [grokify/ringcentral-oauth-demos#23]
Now we have official Ruby SDK https://github.com/ringcentral/ringcentral-ruby

It's time to update the ruby demo to use it.

**Comment by grokify** [comment]
Added in 219771b47972402ef5ae66e0d71ba59be01a722e

Requires fix in [`ringcentral/ringcentral-ruby/commit/910a4ed`](https://github.com/ringcentral/ringcentral-ruby/commit/910a4edc1e71c19b751a71af33f69a0c7a85b15c)

**Comment by tylerlong** [comment]
Thanks and I published a new version of the Ruby SDK which contains your fix.
